package slogo.internalbackend.commands;

import slogo.internalfrontend.Turtle;

import java.util.List;

/**
 * @author Megan Lemcke, Samantha Whitt
 * Interface for our commands. They will be generated by the ModelManager via reflection to be executed
 * by the BackendExecutor per each command
 */

@FunctionalInterface
public interface Command {

    /**
     * Calculates whatever is needed in the backend for the frontend/command
     * @param args
     * @return necessary value to the parser
     */
    double calculate(Turtle myTurtle, List<Double> args);
}
