package slogo.externalbackend.commands;

import slogo.externalbackend.ParserManager;

import java.util.ArrayList;

/**
 * @author Samantha Whitt
 * Interface for our parser specific commands
 * They are generated by CommandParser and called before backend and frontend are referenced/updated
 */
public interface ControlCommand {

    /**
     * calls on a specific method that possibly alters the how the parser functions or adds things to
     * backend/frontend rules appropriately
     * @param myManager
     * @param arguments
     * @return
     */
    public double execute(ParserManager myManager, ArrayList<String> arguments) throws Exception;
}
